import { actionCallFn } from "./actionCallFn.js";
import { addonCallFn } from "./addonCallFn.js";
import { register as register_ai } from "./ai/register.js";
import { aiFn } from "./aiFn.js";
import { register as register_api } from "./api/register.js";
import { apiFn } from "./apiFn.js";
import { register as register_array } from "./array/register.js";
import { arrayFn } from "./arrayFn.js";
import { register as register_cloud } from "./cloud/register.js";
import { cloudFn } from "./cloudFn.js";
import { controlFn } from "./controlFn.js";
import { register as register_controls } from "./controls/register.js";
import { register as register_db } from "./db/register.js";
import { dbFn } from "./dbFn.js";
import { register as register_debug } from "./debug/register.js";
import { debugFn } from "./debugFn.js";
import { register as register_expect } from "./expect/register.js";
import { register as register_math } from "./math/register.js";
import { mathFn } from "./mathFn.js";
import { middlewareCallFn } from "./middlewareCallFn.js";
import { register as register_object } from "./object/register.js";
import { objectFn } from "./objectFn.js";
import { register as register_redis } from "./redis/register.js";
import { redisFn } from "./redisFn.js";
import { register as register_schema } from "./schema/register.js";
import { register as register_security } from "./security/register.js";
import { securityFn } from "./securityFn.js";
import { register as register_storage } from "./storage/register.js";
import { storageFn } from "./storageFn.js";
import { register as register_stream } from "./stream/register.js";
import { streamFn } from "./streamFn.js";
import { register as register_text } from "./text/register.js";
import { textFn } from "./textFn.js";
import { toolCallFn } from "./toolCallFn.js";
import { unitExpectFn } from "./unitExpectFn.js";
import { register as register_util } from "./util/register.js";
import { utilFn } from "./utilFn.js";
import { varFn } from "./varFn.js";
import { webflowFn } from "./webflowFn.js";
import { workflowExpectFn } from "./workflowExpectFn.js";
import { register as register_zip } from "./zip/register.js";
import { zipFn } from "./zipFn.js";

/**
 * Registers all the parsers in this folder
 * @param {import('../base_parser.js').XanoBaseParser} $
 */
export const register = ($) => {
  $.addonCallFn = $.RULE("addonCallFn", addonCallFn($));
  $.actionCallFn = $.RULE("actionCallFn", actionCallFn($));
  $.middlewareCallFn = $.RULE("middlewareCallFn", middlewareCallFn($));
  $.aiFn = $.RULE("aiFn", aiFn($));
  $.apiFn = $.RULE("apiFn", apiFn($));
  $.webflowFn = $.RULE("webflowFn", webflowFn($));
  $.arrayFn = $.RULE("arrayFn", arrayFn($));
  $.cloudFn = $.RULE("cloudFn", cloudFn($));
  $.controlFn = $.RULE("controlFn", controlFn($));
  $.dbFn = $.RULE("dbFn", dbFn($));
  $.debugFn = $.RULE("debugFn", debugFn($));
  $.mathFn = $.RULE("mathFn", mathFn($));
  $.objectFn = $.RULE("objectFn", objectFn($));
  $.redisFn = $.RULE("redisFn", redisFn($));
  $.securityFn = $.RULE("securityFn", securityFn($));
  $.storageFn = $.RULE("storageFn", storageFn($));
  $.streamFn = $.RULE("streamFn", streamFn($));
  $.textFn = $.RULE("textFn", textFn($));
  $.utilFn = $.RULE("utilFn", utilFn($));
  $.varFn = $.RULE("varFn", varFn($));
  $.zipFn = $.RULE("zipFn", zipFn($));
  $.unitExpectFn = $.RULE("unitExpectFn", unitExpectFn($));
  $.workflowExpectFn = $.RULE("workflowExpectFn", workflowExpectFn($));
  $.toolCallFn = $.RULE("toolCallFn", toolCallFn($));
  register_ai($);
  register_schema($);
  register_api($);
  register_array($);
  register_cloud($);
  register_controls($);
  register_db($);
  register_debug($);
  register_math($);
  register_object($);
  register_redis($);
  register_security($);
  register_storage($);
  register_stream($);
  register_text($);
  register_util($);
  register_zip($);
  register_expect($);
};
